version: "3.9"
services:
  backend:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M
    networks:
      - app
  db:
    container_name: postgres-database
    image: postgres:14.5-alpine
    ports:
      # throw database ports only for local access
      - "127.0.0.1:5432:5432"
    networks:
      - app
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M
networks:
  app:
    name: app
