version: "3.9"
services:
  db:
    container_name: postgres-database
    image: postgres:14.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: qwe
      POSTGRES_DB: db
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.5"
        reservations:
          memory: 128M
