version: "3.9"
services:
  backend:
    container_name: node-backend
    build: .
    environment:
      PORT: 443
    ports:
      - 443:443
    links:
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M
  postgresql:
    container_name: postgres-database
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M
