version: "3.9"
services:
  backend:
    container_name: node-backend
    build: .
    environment:
      PG_CONNECTION_STRING: "postgres://postgres:password@db"
      DEBUG: "*"
    ports:
      - 443:443
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M
  db:
    container_name: postgres-database
    image: postgres:13.4-alpine
    environment:
      POSTGRES_PASSWORD: password
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M
  # admin panel for database
  adminer:
    image: adminer
    ports:
      - 8080:8080
