version: "3.9"
services:
  backend:
    container_name: node-backend
    image: localhost:5000/${PROJECT_NAME}/node-backend
    env_file:
      - .env
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M
    networks:
      - app
  db:
    container_name: node-backend-database
    image: postgres:15.0-alpine
    ports:
      # throw database ports only for local access via ssh
      - "127.0.0.1:5432:5432"
    networks:
      - app
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M
networks:
  app:
    name: app
