# файл миграции
version: "3.9"
services:
  migration:
    build:
      dockerfile: ./src/migration/Dockerfile
      context: .
    environment:
      PG_CONNECTION_STRING: "postgres://postgres:password@db"
    depends_on:
      - db
